### ISSUE TITLE
Adição e remoção de skin

### ISSUE THREAD

**Issue by RafaelGiro** [RafaelGiro/5pots#42]
#### Cenário:  Adição de uma nova skin

- Dado que sou um admin editando um patch notes.
- Quando precisar adicionar uma seção para uma nova skin.
- Então na tela de edição dentro da seção de skins deve ter um botão para adicionar um novo bloco para uma skin.

#### Cenário:  Remoção de uma nova skin

- Dado que sou um admin editando um patch notes.
- Quando precisar remover a seção de uma skin.
- Então na tela de edição para cada skin deve ter um botão para remover o bloco.

#### Cenário:  Reordenação das skins

- Dado que sou um admin editando um patch notes.
- Quando precisar ordenar os blocos de skins.
- Então na tela de edição para cada skin deve ter 2 botoões com flechas para cima e para baixo para ordenar o bloco.

**Comment by rafaelgiro** [comment]
Feito no 4893f30
