### ISSUE TITLE
Upload de chromas

### ISSUE THREAD

**Issue by RafaelGiro** [RafaelGiro/5pots#45]
#### Cenário:  Upload de chroma

- Dado que sou um admin editando um patch notes.
- Quando for fazer upload de chromas, sendo apenas um ou vários
- Então a imagem é mostrada na tela, porém o upload só é feito na hora de salvar.

#### Cenário:  Adição da cor do chroma

- Dado que sou um admin editando um patch notes.
- Quando tiver realizado upload e um chroma.
- Então deverá exibir um input para incluir o hexadecimal do chroma.

#### Cenário:  Reordenação dos chromas

- Dado que sou um admin editando um patch notes.
- Quando precisar ordenar os chromas.
- Então deve ser exibido botões que irão definir a posição do chroma junto com o ID da skin.

**Comment by rafaelgiro** [comment]
Feito no 7b9d20a
