### ISSUE TITLE
Ajustes finais da visualização de skins

### ISSUE THREAD

**Issue by RafaelGiro** [RafaelGiro/5pots#46]
#### Cenário: Lightbox dinâmica

- Dado que sou um usuário visualizando o patch notes.
- Quando quiser ver a imagem no tamanho original.
- E clicar na imagem para abrir a lightbox.
- Então a imagem que eu clicar deve abrir como destaque.

#### Cenário: Navegação da lightbox

- Dado que sou um usuário com a lightbox aberta.
- Quando for ver as outras imagens.
- Então a lightbox deve respeitar a ordem de exibição do site na sua navegação.

#### Cenário: Navegação do post

- Dado que sou um usuário visualizando o post de patch notes.
- Quando abrir o menu de navegação ou estiver no topo do post
- Então deve ser exibido a splash art e nome com um link âncora para a skin.

**Comment by rafaelgiro** [comment]
Feito no 70a251b.

Desisti da lightbox
